name: Deploy Dev

on:
  push:
    branches:
      - develop

jobs:
  deploy-dev:
    runs-on: self-hosted-27

    steps:
      - name: Checkout
        run: git clone ${{ gitea.server_url }}/${{ gitea.repository }} .

      - name: Build Docker image
        run: |
          set -e

          docker build \
            -t b-mori:dev-${{ gitea.sha }} \
            -t b-mori:dev \
            .          

      - name: Deploy locally (Docker via socket)
        run: |
          set -e

          docker stop b-mori-dev || true
          docker rm b-mori-dev || true

          docker run -d \
            --name b-mori-dev \
            -p 8081:80 \
            b-mori:dev-${{ gitea.sha }}
          
                      